Serilog:
  Using:
    - Serilog.Sinks.Console
  Enrich:
    - WithThreadId
    - WithThreadName
    - WithMachineName
    - WithEnvironmentName
    - WithEnvironmentUserName
    - FromLogContext
  MinimumLevel:
    Default: Debug
    Override:
      System: Warning
      Microsoft: Information
      Charon: Information
      Charon.SDL3: Warning
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj} <{SourceContext}>{NewLine}{Exception}"
